#!/bin/sh

echo "Running pre-commit hook..."

# If Code/format.sh faiils, abort the commit
./Code/format.sh
if [ $? -ne 0 ]; then
    echo "Code formatting failed for C/C++. Please fix the issues before committing."
    exit 1
fi

python ./Scripts/FormatPython.py --check-only
if [ $? -ne 0 ]; then
    echo "Code formatting failed for Python. Please fix the issues before committing."
    exit 1
fi